### ISSUE TITLE
matrix_upload has wrong hashbang.

### ISSUE THREAD

**Issue by AXGKl** [poljar/weechat-matrix#102]
The matrix_upload script will never work in any sandboxed python (conda, venv, ...) environment, since it starts with:

    #!/usr/bin/python3 -u

Must be:

```
(weechat) [root@fed30 contrib]# head -n1 matrix_upload 
#!/usr/bin/env -S python3 -u
```

Cheers,
G.

PS:  Maybe this one is related(?)
https://github.com/poljar/weechat-matrix/issues/83

**Comment by poljar** [comment]
I don't know if #83 is related, the user doesn't seem to be running matrix_upload under a sandboxed environment. Care to provide a patch?
