### ISSUE TITLE
go.py shows raw room ids instead of channel names

### ISSUE THREAD

**Issue by rschulman** [poljar/weechat-matrix#107]
The go.py script is giving me the room IDs instead of names, making it hard to get around in Weechat.

I'm running Weechat 2.5, using the master branch of weechat-matrix from just a few commits ago, on a Macintosh.

**Comment by poljar** [comment]
go.py by default uses the full buffer name, for various reasons the full buffer name has to be the room_id in weechat-matrix.

You can set `plugins.var.python.go.short_name "on"` so go.py uses the short name which  is human readable.

Alternatively you can set `matrix.look.human_buffer_names on`, but you'll have to edit your logger setup before you set that option.

**Comment by rschulman** [comment]
Thank you! That's what I was missing.
