### ISSUE TITLE
latest git pull broke something

### ISSUE THREAD

**Issue by ReK2Fernandez** [poljar/weechat-matrix#108]
```
weechat     | nio.responses: Error validating response: 'user_id' is a required property
```

**Comment by poljar** [comment]
Can you give a little bit more details on what is going on here? 

What are you expecting it to do. What is it doing instead?
What steps are needed to reproduce the error? Can you reproduce it?

Such an error can be perfectly normal if the server sends a non 200 response.

**Comment by ReK2Fernandez** [comment]
hello, im not doing anything at all, it was working then I left to eat came
back closed weechat, dediced to check for updates so did a git pull, then
make install
Istarted it like I always do and now I get this.

**Comment by poljar** [comment]
So logging in doesn't work? Did you update nio as well? What is set as the hostname (only the structure of the setting is needed, you can redact the hostname of your server).

**Comment by ReK2Fernandez** [comment]
yeah but I did another git pull and notice you added the nio package to requirements and now works.
