### ISSUE TITLE
Markdown handling doesn't match Riot. Can't send asterisk.

### ISSUE THREAD

**Issue by TheCycoONE** [poljar/weechat-matrix#111]
There are differences between the behavior of Riot and weechat-matrix when it comes to handling asterisks.

In Riot, a lone asterisk in a message (when not the first character) is printed out as is:
`test *word` => test \*word

In weechat-matrix the asterisk until the end of the input is made italics.
`test *word` => test *word*

In Riot you can escape an asterisk by preceding it with a `\`
`test \*word\*` => test \*word\*

In weechat-matrix the escaping makes no difference.
`test \*word\*` => test \\*word*\\

In Riot a ** results in bold test
`test **word**` => test **word**

In weechat-matrix a `**` does not result in anything being printed
`test **word**` => test word

With these restrictions it's not possible to type certain messages. I had a brief look at where this is handled: https://github.com/poljar/weechat-matrix/blob/dc97101d47187f15e106579200ad0d17e9e67192/matrix/colors.py#L121

It might be worth using a third party Markdown library to handle more of the edge cases properly.

**Comment by poljar** [comment]
As already mentioned in the matrix room, there is a branch that uses a markdown parser for input parsing. Sadly the development on this branch stalled.

For reference this is the last status update: https://github.com/poljar/weechat-matrix/issues/44#issuecomment-479631329.
