### ISSUE TITLE
Use weechat's secured data for credentials

### ISSUE THREAD

**Issue by bertalanp99** [poljar/weechat-matrix#115]
I like not keeping my server credentials as plain text as they would appear in the config if I just `/set matrix.server.myserver.address my.server.address` for example.

I use weechat's *secured data* feature. I have set my server address like `/secure set serveraddr my.server.address` and then tried to configure this script using that:

`/set matrix.server.myserver.address ${sec.data.serveraddr}`

However, it seems that the server address is being set *literally* to '${sec.data.serveraddr}' and I get a 'no address associated with name' error (naturally).

I tried setting 'my.server.address' without the secure trickery and it works.

Is this expected behaviour? Maybe `${sec.data.foo}` can only be used for the password?

**Comment by weechatter** [comment]
Very easy to implement, for example:

password = weechat.string_eval_expression(weechat.config_get_plugin('password'), {}, {}, {})

**Comment by poljar** [comment]
Did you try your example with the password field? The help for the password setting states that it is evaluated as well.

It is true that the IRC plugin evaluates all the server options, and we should probably support this as well.

**Comment by bertalanp99** [comment]
I just tried with the password field—it works.
