### ISSUE TITLE
How to do basic setup for testing/dev?

### ISSUE THREAD

**Issue by rexroni** [poljar/weechat-matrix#12]
I read the TODO.md and it looks like this project has a lot of functionality already.  However, when I downloaded it and ran `make install`, opened weechat, and called `/python load matrx`, I get the following error:

python: function "register" not found (or failed) in file: "$HOME/.weechat/python/matrix"

Am I missing something basic?  Could it be a python2 vs python3 issue? (my system runs python3 by default).

Anyway, I also saw that no work has been done on the OLM portion of the code, which my friend and I have been learning about to try to fix the [lua matrix plugin](https://github.com/torhve/weechat-matrix-protocol-script).  We could potentially help with your project as well.

Is it ready for the encryption to be added?

**Comment by poljar** [comment]
The script is loaded using `/script load matrix`. It supports python2 as well
as python3.

OLM support is in the works, there's an encryption branch and there are
more unpublished commits in my private git repo.

The code is currently in a state of flux so contributions are a bit hard to
coordinate at this time.

Some safe places to contribute are: Tests,
documentation, commands.py, bar_items.py, completions.py, and adding more
configuration options. A big refactor of the rest of the codebase is planned
after OLM support lands.

You're also welcome to join us on #weechat-matrix:termina.org.uk for development
related discussions.

**Comment by rexroni** [comment]
I would add for posterity's sake that I had to install webcolors and http_parser for python2 before it worked.  Also the command was `/script load matrix.py`, not `/script load matrix`

**Comment by dkasak** [comment]
Yeah, thanks for that. I was going to write down all the dependencies of the script but never got around it, so this is a good start.

We'll add a better README/instructions once the code settles down a bit. Patches welcome, of course. ;)
