### ISSUE TITLE
Passphrase for riot-keys.txt not escaped.

### ISSUE THREAD

**Issue by dngray** [poljar/weechat-matrix#121]
When importing ie `/olm import riot-keys.txt <passphrase>` it seems the passphrase is not escaped causing an error like:

```
matrix: Error importing keys: [Errno 2] No such file or directory: 'riot-keys.txt'  
matrix: Succesfully imported keys
```

**Comment by almereyda** [comment]
Thanks for mentioning how to import `riot-keys.txt`. This could also be added to the readme.

**Comment by dngray** [comment]
I tested this again and cannot seem to reproduce, using a complex password like `HFPx?2"dHn6NEx\kSaG2$Y}=+CaOP#2X0{<b!}PwKv,Ozphl@+`

I don't get the error importing the file, and it seems to load the keys.
