### ISSUE TITLE
Best way for getting sound notifications?

### ISSUE THREAD

**Issue by MRAAGH** [poljar/weechat-matrix#143]
I want to have a sound play whenever I receive a message in any matrix buffer. I've looked at existing Weechat plugins, but it appears all the sound plugins are specific to IRC.

Then, I decided to try to make a little plugin on my own. However, I can't find the right api hook for this purpose. I was only able to find documentation for irc hooks.

My question is, is this possible? Or, should I instead edit the code of weechat-matrix plugin itself? I apologize if this is a noob question, I am totally new to Weechat.

**Comment by poljar** [comment]
Many of the signals/hooks are generic, for example the beep trigger works for the IRC plugin as well as for the weechat-matrix script. This is mostly achieved using the [hook_print](https://weechat.org/files/doc/stable/weechat_plugin_api.en.html#_hook_print) API.

If `hook_print` isn't enough for you I suggest adding a signal to Weechat-matrix itself that you can then hook into using your own little plugin.

**Comment by MRAAGH** [comment]
Oh, I was actually trying with hook_print before, but I did not realize "tags" exist until now. Now I know how to do this, thank you!

**Comment by MRAAGH** [comment]
It's done and it's working great! I'll close this.
