### ISSUE TITLE
Adding weechat-matrix to weechat script list?

### ISSUE THREAD

**Issue by pretentious7** [poljar/weechat-matrix#147]
Are there any plans to add weechat-matrix to weechat's scriptlist? Weechat's script autoload doesn't automatically work on scripts not in the list, which is not ideal.

This can be solved by manually putting the script in the autoload for the particular language, as detailed here https://weechat.org/files/doc/stable/weechat_scripting.en.html#load_script 

I'll try and add this to the readme soon as I can figure out how to haha.

**Comment by poljar** [comment]
To enable autoload just symlink matrix.py to the autoload folder.
The Weechat scriptlist requires scripts to be a single file, it is not feasible to do this with this script.

The planned way to solve distribution problems is to rewrite the script in Rust and turn it into a plugin.

**Comment by pretentious7** [comment]
ah yea that's what I did. Speaking of autoloads, is there a way to autorun the matrix connect command at startup?

Also do you think this should be in the readme? or is just having the closed issue good enough? I'm sort of new to the free software community, don't really know how granular the readme.me page is intended to be.

**Comment by poljar** [comment]
Every server has an `autoconnect` setting, just like the IRC plugin.

The Weechat documentation already contains this, we don't want to replicate all of the Weechat docs in the readme. That being said if you think that this is a common pitfall for newcomers feel free to open a PR that adds it.

**Comment by kdb424** [comment]
Being a newcomer to weechat and weechat matrix, I've run /set matrix.server.matrix_org.autoconnect on and still don't seem to be autoconnecting. I may be misunderstanding the docs (matrix plugin is loaded), and running
```
/matrix connect matrix_org
```
does in fact connect, but upon relaunch, I still have to run that.

**Comment by poljar** [comment]
Did you run `/save` when you changed the option? Weechat doesn't store settings automatically unless you set the `weechat.look.save_config_on_exit` option.

**Comment by kdb424** [comment]
I.... don't know how I missed save on that step. Sorry for wasting your time, and thank you for the quick responses.
