### ISSUE TITLE
Make highlights in urls suppressable

### ISSUE THREAD

**Issue by maralorn** [poljar/weechat-matrix#157]
Thank you for weechat-matrix. It‘s great.

I have a corner case issue: My nick is a sub string of my server domain.

That means that on every image or other media item posted to a channel I get a highlight. That renders highlights in large rooms quite unusable for me because I become conditioned to ignore them.

I have tried fixing this with weechat plugins. Like [unhighlight](https://weechat.org/scripts/source/unhighlight.py.html/) but they do something like replacing the message with an additional `no_highlight` tag. (I am a bit fuzzy on the details.) The code says:
```
    # inspired by https://weechat.org/scripts/source/mass_hl_blocker.pl.html/
    # this is terrible and gross but afaik there is no way to change the
    # highlight message once it's set and no way to interact with a message's
    # tags before highlights are checked.
```
So I tried to use this with my matrix buffers, but it didn‘t seem to have any effect. So I suspect this is relying on some implementation details of the irc buffers.

So maybe we could add an option to weechat-matrix to suppress the highlight in the first place? Otherwise I am obviously open to any other workaround you can think of.

Any help would be highly appreciated! Thanks in advance.

**Comment by poljar** [comment]
Uhm, I'm not really sure how to handle this. The IRC plugin has some settings to restrict highlights to some tags, maybe that could be added.

The only place where we setup some highlight settings is here https://github.com/poljar/weechat-matrix/blob/master/matrix/buffer.py#L417.

As far as I understand the `unhighlight` script should work.

**Comment by maralorn** [comment]
Oh, wow. Thanks for the hint. I somehow didn‘t know/understand the highlight_words variable. I‘ll just use buffer autoset to unset that variable and use a highlight_regex instead. That‘ll work fine. Thx!
