### ISSUE TITLE
some nicks are really long and make the chat area tiny

### ISSUE THREAD

**Issue by ftyers** [poljar/weechat-matrix#158]
Could it be possible to have a maxlength for nicks/channel names? e.g. 8chars and then just have ellipses or something?

https://www.imgpaste.net/image/85TbT

**Comment by poljar** [comment]
The `weechat.look.prefix_align_max` setting already does that.

**Comment by ftyers** [comment]
Excellent thanks! I'll try it out now.

**Comment by ftyers** [comment]
For the side bar (userlist) `/set weechat.bar.nicklist.size_max 12`
