### ISSUE TITLE
matrix_decrypt(1): default to --plumber=xdg-open?

### ISSUE THREAD

**Issue by emilazy** [poljar/weechat-matrix#159]
Currently the hardcoded default is `/usr/bin/rifle`, which is specific to ranger users and unnecessarily hardcodes an exact path. I think `xdg-open` would be a more universal default.

**Comment by poljar** [comment]
The script [has](https://github.com/poljar/weechat-matrix/blob/master/contrib/matrix_decrypt#L71) a `--plumber` command-line switch. Users can easily create wrappers that set up this option to their liking.

We could possibly add a setting that sets the plumber option from within Weechat though but I won't spend time on this currently.

**Comment by emilazy** [comment]
Thanks!
