### ISSUE TITLE
Question about Dockerfile

### ISSUE THREAD

**Issue by fazlerabbi37** [poljar/weechat-matrix#165]
Hi, I am trying to use weechat-matrix in an Ubuntu system and was trying to install using Dockerfile. Though I did not find any instructions, I decided to give it a try as I have a little experience with Docker. After reading the Dockerfile I am a bit confused as to how the Dockerfile is intended to use. Here is what I found confusing:

1. At [Line 20](https://github.com/poljar/weechat-matrix/blob/21eba25633be93cd750a82c6f565967bba2896d8/Dockerfile#L20) why are we cloning the repository **inside the Docker image**? AFAIK, people generally DON'T download Dockerfile alone from a repo but clone the repo and the build the image. 

2. Again, [Line 28](https://github.com/poljar/weechat-matrix/blob/21eba25633be93cd750a82c6f565967bba2896d8/Dockerfile#L28) we are creating a directory **inside the Docker image** for weechat autoload and linking the compiled file to that directory **inside the Docker image**.

We are not going to run weechat or weechat-matrix inside a docker container created from the image, are we? 

I know this wouldn't be a perfect example but if we look at [docker doc: Quickstart: Compose and Django](https://docs.docker.com/compose/django/#define-the-project-components) and on [documentation for official python docker image](https://github.com/docker-library/docs/tree/master/python#create-a-dockerfile-in-your-python-app-project) we would see that - 

- files are copied from the host to container
- only the dependency installation is done inside the container

Also, the official python docker image has a Debian slim tag. Can't we use that?

It would be really helpful, if these confusions are cleared as the Dockerfile would be really helpful for installation and may solve many problems related to installation and dependency.

**Comment by poljar** [comment]
>  At [Line 20](https://github.com/poljar/weechat-matrix/blob/21eba25633be93cd750a82c6f565967bba2896d8/Dockerfile#L20) why are we cloning the repository **inside the Docker image**? AFAIK, people generally DON'T download Dockerfile alone from a repo but clone the repo and the build the image.

I don't know what people generally do with docker nor have I written the docker file. I assume that it's done so that the docker file is self contained.
 
> We are not going to run weechat or weechat-matrix inside a docker container created from the image, are we?

I believe that this was the intention of the docker file authors.
 
> Also, the official python docker image has a Debian slim tag. Can't we use that?

I don't know.

> It would be really helpful, if these confusions are cleared as the Dockerfile would be really helpful for installation and may solve many problems related to installation and dependency.

What problems did you run into? I never tried the docker file myself but I believe some people are using it successfully.

**Comment by fazlerabbi37** [comment]
> I believe that this was the intention of the docker file authors.

understood.

> I believe that this was the intention of the docker file authors.

if that is so than that would clear up all the questions. 

> What problems did you run into? I never tried the docker file myself but I believe some people are using it successfully.

I am trying to use the Dockerfile in a way that it would install the requirements from the `requirements.txt` and later we will run `make install` in the host using the docker image thus the final complied program is in the host, not inside a container. This would allow us to copy or link the files to the hosts weechat autoload directory. 

I think the Dockerfile was created by @ptman and later modified by @nibalizer to support Python 3. Maybe you guys want to share your thoughts? (apologies in advance for the out of blue mention)

**Comment by ptman** [comment]
No worries about the mention.

The idea was specifically to run weechat and all dependencies inside docker. There were lots of people with trouble installing the dependencies on their host distribution. But maybe the situation has changed?

**Comment by poljar** [comment]
I think that the problem is that there is no final compiled program. If all the requirements are installed weechat-matrix is just a bunch of python scripts that Weechat executes.

In the past the docker image compiled libolm (the C library) but nowadays we use one from the Debian repo.

**Comment by fazlerabbi37** [comment]
> I think that the problem is that there is no final compiled program. If all the requirements are installed weechat-matrix is just a bunch of python scripts that Weechat executes.

I have 0 knowledge of Makefile, so I am lost try to understand it. As described in the README's installation instruction, we install the `libolm` dependency, then we install all the dependencies with `pip` then what does the `make install` command do?

> In the past the docker image compiled libolm (the C library) but nowadays we use one from the Debian repo.

Is `libolm` a run time requirement or just needed during `pip install`?

**Comment by trygveaa** [comment]
`make install` just copies files to the weechat directory. All the dependencies are runtime, so if you're not running weechat inside docker, the Dockerfile won't help you at all.

> Also, the official python docker image has a Debian slim tag. Can't we use that?

The Dockerfile already uses slim? `FROM debian:testing-slim`

**Comment by fazlerabbi37** [comment]
> make install just copies files to the weechat directory. All the dependencies are runtime, so if you're not running weechat inside docker, the Dockerfile won't help you at all.

thanks! if dependencies are run time the Docker is of no use for me. :disappointed: 

> The Dockerfile already uses slim? FROM debian:testing-slim

I thought that the Dockerfile is for installing the `pip` dependencies that's why I asked why not use the official python image but from the conversation above what I understood, the Docker image was specifically for running weechat and weechat-matrix inside a container.

**Comment by trygveaa** [comment]
If you don't want to install the dependencies globally, running `pip` inside a virtualenv is probably what you should do. Or, what are you trying to accomplish?

**Comment by fazlerabbi37** [comment]
I did install weechat-matrix with virtualenv and pip. :smile:
