### ISSUE TITLE
validating response: 'flows' is a required property

### ISSUE THREAD

**Issue by o11y21** [poljar/weechat-matrix#168]
I get stuck on connection with same error on two matrix instances with:

        nio.http: Handling Http2 event: <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=128), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=65536), ChangedSetting(setting=SettingCodes.MAX_FRAME_SIZE, original_value=16384, new_value=16777215)}>
        nio.http: Handling Http2 event: <WindowUpdated stream_id:0, delta:2147418112>
        nio.http: Handling Http2 event: <SettingsAcknowledged changed_settings:{}>
        nio.http: Handling Http2 event: <ResponseReceived stream_id:1, headers:[(b':status', b'404'), (b'server', b'nginx'), (b'date', b'Thu, 26 Mar 2020 17:35:11 GMT'), (b'content-type', b'text/html'), (b'content-length', b'162'), (b'vary', b'Accept-Encoding')]>
        nio.http: Handling Http2 event: <DataReceived stream_id:1, flow_controlled_length:162, data:3c68746d6c3e0d0a3c686561643e3c7469746c65>
        nio.http: Handling Http2 event: <StreamEnded stream_id:1>
        nio.client: Error with response of type type: <class 'nio.responses.LoginInfoResponse'>, error code 404
        nio.responses: Validating response schema
        nio.responses: Error validating response: 'flows' is a required property
        nio.client: Received new response of type LoginInfoError

Has anyone a clue for me? Tried it with python3.8 and others...

**Comment by poljar** [comment]
What does this command return?
```
curl https://$your_homeserver/_matrix/login
```

Don't forget to change the homeserver to your real one. It seems like you're getting a 404 for that.

**Comment by o11y21** [comment]
thanx a lot. I was a little blind then - 🤦🏻. I though having tested URLs, but indeed both where wrong, one of them seems not to provide _matrix/login nevertheless.
