### ISSUE TITLE
Random disconnected

### ISSUE THREAD

**Issue by caywin25** [poljar/weechat-matrix#195]
Hello 
I could notice that from time to time randomly I have this error that appears:

```
12:08 - matrix: Invalid input ConnectionInputs.RECV_WINDOW_UPDATE in state ConnectionState.CLOSED
12:08 -- matrix: disconnected from server
12:08 -- matrix: reconnecting to server in 10 seconds
12:08 -- matrix: reconnecting to server...
```
I am auto reconnected then.
I don't understand why the connection is closing on its own.

Thank you

**Comment by poljar** [comment]
The server is disconnecting you because we're using a single socket instead of a connection pool. There are plenty of examples how to mitigate this if you're using your own server, [here](https://github.com/poljar/weechat-matrix/issues/123#issuecomment-543573043) for example.

**Comment by caywin25** [comment]
Ah thank you :)

Seems to be ok now.
Regards
