### ISSUE TITLE
cannot navigate to rooms by name quickly with go plugin

### ISSUE THREAD

**Issue by Soundtoxin** [poljar/weechat-matrix#210]
My list of rooms and contacts shows pretty simple names, but when I try to go to them with the "go" plugin they are named gibberish like `servername.!aoeuaoeuaoeuaoeu:servername`. The fastest way to jump to them is by their number, which requires me to read through the whole list of stuff to find the number next to the name, instead of just getting there at the speed of thought. I swear with the older lua matrix plugin I was able to jump to rooms by name no problem.

**Comment by Soundtoxin** [comment]
`go.py` should work with partial names, so even if the hash stayed in the buffer name but the short_name of the buffer was also part of the normal name, it would solve this problem I think.
Also worth noting that both Riot and Nheko have a bind for searching/filtering rooms and jumping to them (ctrl-k), so it should be a thing here as well.

**Comment by poljar** [comment]
We can't use sensible names for the full buffer name since we can have duplicate names in Matrix land, the logger plugin complains otherwise.

You can set `/set plugins.var.python.go.short_name "on"` to make go.py work or set `/set matrix.look.human_buffer_names on`, that way the full buffer name will get a nice name but beware that you need to edit your logger setup for that to work.

**Comment by Soundtoxin** [comment]
> We can't use sensible names for the full buffer name since we can have duplicate names in Matrix land

What about adding the info from the sensible names to the existing buffer names (nothing gets removed) just so they show up as expected in searches? This doesn't make them any less unique, just makes the names a bit longer to add all the info in one place.



> You can set `/set plugins.var.python.go.short_name "on"` to make go.py work

Thanks, maybe I'll just do this.



> or set `/set matrix.look.human_buffer_names on`

I tried this and it didn't seem to have any effect before or after a restart, and it sounds like it wouldn't be ideal anyway considering the duplicates issue. I actually have three people in my contacts list who I've added two matrix accounts for, and they all use the same name on both networks.

**Comment by poljar** [comment]
> What about adding the info from the sensible names to the existing buffer names (nothing gets removed) just so they show up as expected in searches? This doesn't make them any less unique, just makes the names a bit longer to add all the info in one place.

The problem with that is that the sensible names can and will change, so your log file will change as well.

**Comment by Soundtoxin** [comment]
Ah, that makes sense... How terrible. I guess things are probably as good as they'll get then. Thanks for the go.py tip, that'll tide me over for now.
