### ISSUE TITLE
Not understanding how to connect to any channels

### ISSUE THREAD

**Issue by themaster567** [poljar/weechat-matrix#226]
I'm sorry that I'm clogging up more important tickets here, but I'm at the end of my rope. I have poured through all the documentation I can find and more, and I still don't even know how to connect to a channel. I have the list of servers I'm in on the left side, but regardless of if I enter their name with underscores or not with /join, it doesn't work. I do not understand what I am doing wrong. I know I'm an idiot and just missing something obvious, but I don't know where else to turn.

**Comment by poljar** [comment]
This script has a bit of a poor UX to be your only client. The `/join` command does work, you'll either need to get a hold of a room alias or a room id.

So `/join #weechat-matrix:termina.org.uk` should work.

**Comment by q9f** [comment]
> So `/join #weechat-matrix:termina.org.uk` should work.

Unfortunately, it doesn't.

```
            │15:17:27    weechat =!= | Error: ambiguous command "/join": it exists in many plugins and not in "core" plugin
```

**Comment by trygveaa** [comment]
You have to run if from one of the weechat-matrix buffers, you can't run it in the core weechat buffer.

**Comment by q9f** [comment]
Aye, thanks. Just saw #137!

**Comment by ptman** [comment]
solved, close?
