### ISSUE TITLE
Having trouble getting started (Unable to decrypt: The sender's device has not sent us the keys for this message)

### ISSUE THREAD

**Issue by cuppajoeman** [poljar/weechat-matrix#227]
So I followed the steps to login with weechat-matrix, and was able to do so. I then went to one of my chat's and noticed that all the messages looked like this: 
```
22:31 <&teeare> <Unable to decrypt: The sender's device has not sent us the keys for this message>
22:31 <&teeare> <Unable to decrypt: The sender's device has not sent us the keys for this message>
22:31 <&cuppajoeman> <Unable to decrypt: The sender's device has not sent us the keys for this message>
22:31 <&cuppajoeman> <Unable to decrypt: The sender's device has not sent us the keys for this message>
22:32 <&cuppajoeman> <Unable to decrypt: The sender's device has not sent us the keys for this message>
22:38 <&cuppajoeman> <Unable to decrypt: The sender's device has not sent us the keys for this message>
```
I get this in all my private messages, but not in #Matrix-HQ for example, and I think this has something to do with encryption, but not I'm not to sure how to proceed.

I also noticed after logging in that element wanted me to verify the new login. I wasn't exactly sure how to do this on weechat. I found the `olm` command and ran `/olm verify ...` in a matrix buffer which brought up all the verified keys, but I'm not sure if this is the right way to verify my login.

Anyways if anyone has any ideas for me, it would be greatly appreciated!

**Comment by cuppajoeman** [comment]
Nvm, I was able to figure it out with help from the people in the matrix-hq channel, I had to figure out how to start the verification manually (the initial one that popped up on element didn't actually start it in weechat). And then import the keys (weechat froze for a solid couple seconds when I did that), after restarting weechat everything was good.

**Comment by dadaphl** [comment]
Thank you. I was looking for this. Maybe it should be part of the README. Also it was not so clear that i had to export the keys first. When i started using element web it just asked me to copy paste some phrase.
In case somebody gets stuck. You have to export your E2E room keys (from elements web). They will be encrypted with a password that you choose during the export and then downloaded as a TXT file.


1. Export
Go to "All Settings > Security & Privacy" and click on "Export E2E room keys". Choose a fancy password and download the key file.
![Screenshot_2020-10-09_11-43-25](https://user-images.githubusercontent.com/415536/95569089-6042f280-0a25-11eb-890f-8986bb92ce1f.png)

2. Import
After that you can import them in a **matrix buffer** in Weechat with he following command.

```
/olm import ~/Downloads/element-keys.txt myfancypassword1234
```

**Comment by ewtoombs** [comment]
Why is this closed? Verification requests from element web still don't appear. The only notifications that appear are when the verification is cancelled or times out.
