### ISSUE TITLE
Message redaction does not delete message?

### ISSUE THREAD

**Issue by piegamesde** [poljar/weechat-matrix#243]
Apparently, Weechat-Matrix users can see messages from me even though I redacted them. Simply showing redacted messages with a strikethrough bar is not enough. I didn't find any explicit instructions for clients in the spec, but the general expectation (and what other clients do) is to remove besaid message from their local database (if there is one) and show a deleted message placeholder instead.

(Note that I'm not a Weechat-Matrix user myself.)

**Comment by poljar** [comment]
There is a setting which controls the redaction style: `matrix.look.redactions`. You can chose between `strikethrough` (self explanatory), `notice` (only marks that the message has been redacted), `delete` (completely removes the message).

Though I'm not sure how this information is going to help you.

**Comment by piegamesde** [comment]
> I didn't find any explicit instructions for clients in the spec

I asked around and the situation is not that clear. The spec details this in the [room versions](https://matrix.org/docs/spec/rooms/v1#redactions). The server behaviour is pretty explicit:

> Upon receipt of a redaction event, the server must strip off any keys not in the following list: […]
> The content object must also be stripped of all keys, unless it is one of one of the following event types: […]

But for the clients it only says:

> Clients may need to consider some algorithms performed by the server for their own implementation.

**Comment by poljar** [comment]
I'm not sure what kind of instructions you hope to find but as I mentioned the functionality you are seeking is provided.
