### ISSUE TITLE
Login information inside /matrix command

### ISSUE THREAD

**Issue by 0neGuyDev** [poljar/weechat-matrix#249]
It'd be really convenient to be able to do as an example `/matrix logon <username> <password>` or similar, this would make it easy to add multiple accounts.

I dont quite know if there're any limitations that make it hard/impossible to be running two accounts at once. Hopefully not.

**Comment by poljar** [comment]
`/matrix server add server_name_here localhost:8080` adds another account, what should the `logon` subcommand accomplish that isn't already possible?

Multiple accounts are already supported.

**Comment by 0neGuyDev** [comment]
right yeah no im just retarded and didn't realize that was an option...
