### ISSUE TITLE
Is there a way to address users which will notify them?

### ISSUE THREAD

**Issue by phil-s** [poljar/weechat-matrix#250]
In the Element GUI client, typing a user's name in a message does nothing special, but *tab-completing* a user's name causes it to be highlighted locally, and it turns out that the user *only* gets notified if you performed that tab/highlight step.

So Element is evidentially sending something different if you do that (but only showing a highlight, so I can't tell what it's doing).

Is there a way to replicate this in weechat, so that I can address people in a way which causes Matrix to notify them?

**Comment by dkasak** [comment]
The things Element produces when you tab-complete a name are called "pills".

But pills are not required to highlight someone on Element. A simple mention of the name (or maybe even the local part of the MXID, not quite sure about that one) will highlight the user.

Weechat currently does not have support for generating pills.

**Comment by phil-s** [comment]
Thanks for the reply, dkasak.

> But pills are not required to highlight someone on Element. A simple mention of the name (or maybe even the local part of the MXID, not quite sure about that one) will highlight the user.

I saw some documentation to the same effect, but someone told me directly that they didn't get a notification if I just typed their name normally, so my impression was the those docs were not accurate.

I'll have to experiment and follow up here.

**Comment by phil-s** [comment]
Initial testing confirms that I was mistaken about this.  I suspect there may be something going on with the one specific user who told me about the issue, as they have some unusual characters in their name.  I'm going to close this, as I can see that in the general case it works as advertised.  Thanks again for the quick response @dkasak, and my apologies for the noise.

**Comment by schildbach** [comment]
At least on Element notification by mentioning the local part of the ID is configurable. I suspect lots of people have it switched off because it can produce lots of irrelevant notifications if you've got a common local part.

**Comment by phil-s** [comment]
Ah, interesting.  I can't test right now, but since closing this issue I've gathered that you can also address people by prefixing their name with a `@` character, so IIRC `@foo` would notify user `foo`.  I never use that because it hadn't seemed necessary, but perhaps this approach (which I presume will work in weechat) would reliably notify users who have that feature turned off?
