### ISSUE TITLE
[ BUG ] AttributeError: 'MatrixConfig' object has no attribute 'encryption_warning_sign'

### ISSUE THREAD

**Issue by BachoSeven** [poljar/weechat-matrix#253]
Python version: `3.9.1`
weechat version: 2.9
plugin version: updated to master

![image](https://user-images.githubusercontent.com/55460785/102275242-6a053c80-3f25-11eb-9aec-79ccd4fd18ff.png)

**Comment by poljar** [comment]
Serves me right for not trying out pull requests, fixed by https://github.com/poljar/weechat-matrix/commit/e0cae8b418bb43cc46c825137d69e6939409058d

**Comment by BachoSeven** [comment]
Whoa that was fast, thanks!

**Comment by wavexx** [comment]
Mmmh, why I didn't get hit by this though?
