### ISSUE TITLE
Ignoring devices is slow, unable to decrypt

### ISSUE THREAD

**Issue by avdb13** [poljar/weechat-matrix#255]
weechat-matrix is my last hope for a light Matrix client with a TUI, but I always experience problems with it.

1. When I run `/olm import ~/element-key.txt password` after exporting the E2EE key on element.io I still can't decrypt messages sent before the import. After that I can't send messages myself yet because there are +100 people in the room of which 50 have unverified sessions, ignoring them is really resource intensive and slow for some reason.

1. Sending the first message to an E2EE room on a non-matrix.org server takes longer than 10 seconds, after that it's normal again.

Either I'm using this script wrong or it's rewritten in Rust because Python got some serious limitations.

**Comment by poljar** [comment]
The Python environment inside of Weechat has serious limitations, you can't spawn threads so anything that is CPU intense will block the UI. The Rust rewrite on the other hand is using a threadpool and nothing CPU/IO intensive is going on on the UI thread. While it's not yet ready for general usage it is getting quite close to it.

**Comment by avdb13** [comment]
Alright, good luck on the Rust rewrite. Can't wait for it to be stable.
