### ISSUE TITLE
Change whether untrusted devices are ignored by default

### ISSUE THREAD

**Issue by elmehalawi** [poljar/weechat-matrix#257]
If you send a message in a room with untrusted devices, weechat-matrix complains and doesn't send the message. If I send the same message again, it ignores untrusted devices and sends the message anyway.

Is it possible to add an option to always ignore untrusted devices without this song and dance every time? Sorry if there is already one but I missed it.

**Comment by poljar** [comment]
There is not, though the Rust rewrite has this behavior by default.

**Comment by elmehalawi** [comment]
Sounds great, thanks.
