### ISSUE TITLE
Update instructions for Debian

### ISSUE THREAD

**Issue by fmlatghor** [poljar/weechat-matrix#259]
Debian users have had issues getting `weechat-matrix` to install or work. I shall get to this when I actually get `weechat-matrix` working on Debian.

**Comment by scoriess** [comment]
Hey fmlatghor, 

I recently installed weechat-matrix on a rig running on Bullseye. There is a package maintained by Kyle Robbertze <paddatrapper@debian.org>, for details on the package:
`apt-cache show weechat-matrix`

Connection to matrix.org homeserver or a custom homeserver as well as end-to-end encrypted chat in channels work fine. I haven't been able to find how to send or receive direct messages to other users yet though. If you want to give it a try, here are the steps:

Install package:
`apt install weechat-matrix`

Verify where path of installed files:
`dpkg -L weechat-matrix`

They should be in `/usr/lib/x86_64-linux-gnu/weechat/plugins/python/`. This can change according to your platform.

Create two symlinks:
`ln -s /usr/lib/x86_64-linux-gnu/weechat/plugins/python/matrix ~/.weechat/python/matrix` 
`ln -s /usr/lib/x86_64-linux-gnu/weechat/plugins/python/matrix.py  ~/.weechat/python/matrix.py`  

Now that all files required by Weechat are available at the right location, go in Weechat and load `~/.weechat/python/matrix.py`:
`/script load matrix.py`

If the loading was successful, a message similar to the one below should appear in the main buffer (you can see this buffer by using alt+1 keybinding):
```
python: loading script...
python: registered script "matrix", version...
```
Add your custom server. Choose a name (eg. myserver) and specify the hostname (eg. myserver.org):
`/matrix server add myserver myserver.org`

Add the appropriate credentials:
```
/set matrix.server.myserver.username johndoe
/set matrix.server.myserver.password johndoepwd
/save
```

Connect to your custom server "myserver":
`/matrix connect myserver`

**Comment by fmlatghor** [comment]
> Hey fmlatghor,
> 
> I recently installed weechat-matrix on a rig running on Bullseye. There is a package maintained by Kyle Robbertze [paddatrapper@debian.org](mailto:paddatrapper@debian.org), for details on the package:
> `apt-cache show weechat-matrix`
> 
> Connection to matrix.org homeserver or a custom homeserver as well as end-to-end encrypted chat in channels work fine. I haven't been able to find how to send or receive direct messages to other users yet though. If you want to give it a try, here are the steps:
> 
> Install package:
> `apt install weechat-matrix`
> 
> Verify where path of installed files:
> `dpkg -L weechat-matrix`
> 
> They should be in `/usr/lib/x86_64-linux-gnu/weechat/plugins/python/`. This can change according to your platform.
> 
> Create two symlinks:
> `ln -s /usr/lib/x86_64-linux-gnu/weechat/plugins/python/matrix ~/.weechat/python/matrix`
> `ln -s /usr/lib/x86_64-linux-gnu/weechat/plugins/python/matrix.py ~/.weechat/python/matrix.py`
> 
> Now that all files required by Weechat are available at the right location, go in Weechat and load `~/.weechat/python/matrix.py`:
> `/script load matrix.py`
> 
> If the loading was successful, a message similar to the one below should appear in the main buffer (you can see this buffer by using alt+1 keybinding):
> 
> ```
> python: loading script...
> python: registered script "matrix", version...
> ```
> 
> Add your custom server. Choose a name (eg. myserver) and specify the hostname (eg. myserver.org):
> `/matrix server add myserver myserver.org`
> 
> Add the appropriate credentials:
> 
> ```
> /set matrix.server.myserver.username johndoe
> /set matrix.server.myserver.password johndoepwd
> /save
> ```
> 
> Connect to your custom server "myserver":
> `/matrix connect myserver`

Just want to let you know *I've seen this*, I'm just struggling to get my apt sources under control.

**Comment by fmlatghor** [comment]
Should I close this? I've switched to purple-matrix because weechat-matrix is too slow.

**Comment by fmlatghor** [comment]
Rather I am asking if this still needs to be fixed. If there's a package for bullseye, then I think it is, but debian users on older versions might want updated instructions.

**Comment by paddatrapper** [comment]
I just want to add that there is a script in the package that will create the symlinks for you
