### ISSUE TITLE
It forces me to login using SSO

### ISSUE THREAD

**Issue by antoyo** [poljar/weechat-matrix#260]
When I start weechat, it forces me to login using SSO, even though I have a username and password configure.

To fix it, I had to change the start of the function `_handle_login_info ` to:
```python
    def _handle_login_info(self, response):
        if ("m.login.sso" in response.flows
                and (not self.config.username or not self.config.password)):
            self.start_login_sso()
```
I only added a `not` before `self.config.password`.

**Comment by poljar** [comment]
Ah that's clearly a mistake, if you provide a PR with this patch I'll gladly merge this.

**Comment by mcnesium** [comment]
I am facing the same issue, the fix does not seem to work for me (running weechat-matrix on Git tag `0.3.0`) on matrix.org. I get the SSO link notification, even though I *do* have `username` and `password` set.

    matrix: The server requested a single sign-on, please open this URL in your browser. Note that the browser needs to run on the same host as Weechat.
    matrix: https://matrix.org:443/_matrix/client/r0/login/sso/redirect?redirectUrl=http://127.0.0.1:54049

What can I do to get this connected?

Settings copied from `/fset`:

<details>

    matrix.color.error_message_bg                       color    default                                             
    matrix.color.error_message_fg                       color    darkgray                                            
    matrix.color.nick_prefixes                          string   "admin=lightgreen;mod=lightgreen;power=yellow"      
    matrix.color.quote_bg                               color    default                                             
    matrix.color.quote_fg                               color    lightgreen                                          
    matrix.color.unconfirmed_message_bg                 color    default                                             
    matrix.color.unconfirmed_message_fg                 color    darkgray                                            
    matrix.color.untagged_code_bg                       color    default                                             
    matrix.color.untagged_code_fg                       color    blue                                                
    matrix.look.bar_item_typing_notice_prefix           string   "Typing: "                                          
    matrix.look.busy_sign                               string   "⏳"                                                
    matrix.look.code_block_margin                       integer  2                                                   
    matrix.look.code_blocks                             boolean  on                                                  
    matrix.look.disconnect_sign                         string   "❌"                                                
    matrix.look.encrypted_room_sign                     string   "🔒"
    matrix.look.encryption_warning_sign                 string   "⚠️ "                                                
    matrix.look.human_buffer_names                      boolean  off                                                 
    matrix.look.max_typing_notice_item_length           integer  50                                                  
    matrix.look.new_channel_position                    integer  none                                                
    matrix.look.pygments_style                          string   "native"                                            
    matrix.look.quote_wrap                              integer  67                                                  
    matrix.look.redactions                              integer  strikethrough                                       
    matrix.look.server_buffer                           integer  merge_with_core                                     
    matrix.network.autoreconnect_delay_growing          integer  2                                                   
    matrix.network.autoreconnect_delay_max              integer  600                                                 
    matrix.network.debug_buffer                         boolean  off                                                 
    matrix.network.debug_category                       integer  all                                                 
    matrix.network.debug_level                          integer  error                                               
    matrix.network.fetch_backlog_on_pgup                boolean  on                                                  
    matrix.network.lag_min_show                         integer  500                                                 
    matrix.network.lag_reconnect                        integer  90                                                  
    matrix.network.lazy_load_room_users                 boolean  off                                                 
    matrix.network.max_backlog_sync_events              integer  10                                                  
    matrix.network.max_initial_sync_events              integer  30                                                  
    matrix.network.max_nicklist_users                   integer  5000                                                
    matrix.network.print_unconfirmed_messages           boolean  on                                                  
    matrix.network.read_markers_conditions              string   "${markers_enabled}"                                
    matrix.network.resending_ignores_devices            boolean  on                                                  
    matrix.network.typing_notice_conditions             string   "${typing_enabled}"                                 
    matrix.server.matrix_org.address                    string   "matrix.org"
    matrix.server.matrix_org.autoconnect                boolean  off                                                 
    matrix.server.matrix_org.autoreconnect_delay        integer  10                                                  
    matrix.server.matrix_org.device_name                string   "Weechat Matrix"                                    
    matrix.server.matrix_org.password                   string   "********"
    matrix.server.matrix_org.port                       integer  443                                                 
    matrix.server.matrix_org.proxy                      string   ""                                                  
    matrix.server.matrix_org.ssl_verify                 boolean  on                                                  
    matrix.server.matrix_org.sso_helper_listening_port  integer  0                                                   
    matrix.server.matrix_org.username                   string   "mcnesium"

</details>

**Comment by poljar** [comment]
I'm not sure why this would still be failing, I'm using the script on matrix.org as well, setting the if branch to always be false should help but isn't a proper fix: https://github.com/poljar/weechat-matrix/blob/79805d02c4fae473dac41e377b9c97c74e4cff92/matrix/server.py#L1335.

**Comment by mcnesium** [comment]
Nevermind, I am sorry. I thought I could just `git pull` to update the plugin. I did not realize I had to do `make install` to actually create a copy of `matrix.py` in the plugin dir.

It connects now as expected. Thanks a lot for your work :+1:

**Comment by poljar** [comment]
You actually can set up `git pull` to update the installation as well, you just need to symlink the `matrix` folder and `main.py` file into the Weechat Python scripts folder, usually `~/.weechat/python`, note that `main.py` should be symlinked as `matrix.py`.
