### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by vale981** [poljar/weechat-matrix#271]
I am trying to join my matrix account that has a lot of rooms, and I am getting

```
 │23:41:36 weechat     | python: stdout/stderr (matrix): RecursionError: maximum recursion depth exceeded while calling a Python object
│23:41:36 weechat =!= | python: error in function "receive_cb"
```

the infinite recursion is in `parse_event`

**Comment by poljar** [comment]
That's fixed, please update matrix-nio. Relevant issue: https://github.com/poljar/matrix-nio/issues/257.

**Comment by vale981** [comment]
thank  you, that must be the old nix package then :)
