### ISSUE TITLE
Matrix channels don't group under the Matrix server even irc.look.server_buffer = independent 

### ISSUE THREAD

**Issue by mcepl** [poljar/weechat-matrix#280]
Not sure, what to say more. Having the latest weechat-matrix with weechat 3.1 (on openSUSE/Tumbleweed) all IRC channels are nicely grouped under their respective servers, except Matrix channels are all under the last IRC one.

![weechat-screenshot](https://user-images.githubusercontent.com/198999/121900757-10d86300-cd26-11eb-884f-bbe0de4b1683.png)

**Comment by Techman** [comment]
Did you try `/set matrix.look.server_buffer independent`? Matrix is like its own "plugin" in WeeChat, so irc.* settings pertain to only IRC chats.

**Comment by mcepl** [comment]
Right, that seems to help.
