### ISSUE TITLE
Tags for os packagers

### ISSUE THREAD

**Issue by KenMacD** [poljar/weechat-matrix#281]
The [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs) repo is [using tag 0.2.0](https://github.com/NixOS/nixpkgs/blob/2dc9bdf6f2cb1a1f2280d5f06c1810eab6dd39df/pkgs/applications/networking/irc/weechat/scripts/weechat-matrix/default.nix#L24) as that's the last tagged version, but it's rather old.

I know the install instructions just say to use `master`. I can update my build configuration and pick the latest hash easily enough, but I opened this in case you thought more frequent tagging make sense.

**Comment by poljar** [comment]
[0.3.0](https://github.com/poljar/weechat-matrix/releases/tag/0.3.0) is tagged. The project is in maintenance mode since a rewrite is going on, so there won't be that many changes, but pushing tags is easy enough.
