### ISSUE TITLE
README.md tells how to install weechat-matrix but not how to actually run it.

### ISSUE THREAD

**Issue by realisation** [poljar/weechat-matrix#298]
I don't know how to actually run this thing after performing all of the install steps.

**Comment by realisation** [comment]
```
Configuration is completed primarily through the Weechat interface. First start Weechat, and then issue the following commands:
```

I do not even know how to get into the weechat interface.

**Comment by poljar** [comment]
If you don't have Weechat installed, either install it using your package manager or take a look at https://weechat.org/.

If you have it installed run `weechat` from the terminal.

**Comment by realisation** [comment]
Thanks!
