### ISSUE TITLE
Slight inaccuracy in README.md regarding installing Python deps

### ISSUE THREAD

**Issue by kaizushi** [poljar/weechat-matrix#312]
There is a slight issue with the directions in README.md with the dependencies for Python. It tells you to do this, as a normal user...

`pip install -r requirements.txt`

This will actually have problems on a lot of systems as a normal user, and give this error...

`ERROR: (Gentoo) Please run pip with the --user option to avoid breaking python-exec`

It will not give this error if you install it using the **--user** parameter...

`pip install --user -r requirements.txt`

The README.md should be updated to reflect this

**Comment by dkasak** [comment]
Fixed, thanks!
