### ISSUE TITLE
TypeError: TypeChecker() takes no arguments when loading the script

### ISSUE THREAD

**Issue by 2Belette** [poljar/weechat-matrix#317]
Trying weechat-matrix for the first time I got this error when I try  /script load matrix.py :
(Only got python3 on my system)

11:34:47  weechat     | python: stdout/stderr (?):   File "/myuser/.local/share/weechat/python/matrix.py", line 53, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/__init__.py", line 2, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from .client import *
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/client/__init__.py", line 3, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from .base_client import Client, ClientConfig
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/client/base_client.py", line 35, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from ..crypto import ENCRYPTION_ENABLED
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/crypto/__init__.py", line 32, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from .key_request import OutgoingKeyRequest
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/crypto/key_request.py", line 21, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from ..responses import RoomKeyRequestResponse
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/nio/responses.py", line 26, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from jsonschema.exceptions import SchemaError, ValidationError
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/jsonschema/__init__.py", line 21, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     from jsonschema._types import TypeChecker
          │11:34:47  weechat     | python: stdout/stderr (?):   File "/usr/lib/python3.10/site-packages/jsonschema/_types.py", line 168, in <module>
          │11:34:47  weechat     | python: stdout/stderr (?):     draft3_type_checker = TypeChecker(
          │11:34:47  weechat     | python: stdout/stderr (?): TypeError: TypeChecker() takes no arguments
          │11:34:47  weechat =!= | python: unable to parse file "/myuser/.local/share/weechat/python/matrix.py"

**Comment by trygveaa** [comment]
Duplicate of #293.

**Comment by 2Belette** [comment]
Just saw that this seems to be the same issue as #293, not familiar with patching python, what would be the steps to do it ?

**Comment by 2Belette** [comment]
Got it work, I recompiled Python with the patch. It is definitely a duplicate of #293
