### ISSUE TITLE
Seen by (read receipts)

### ISSUE THREAD

**Issue by 2Belette** [poljar/weechat-matrix#318]
Is there a way to see an equivalent of "Seen by" in weechat bar for example ? To know where / what was the last message seen by people in a room / 1:1 chat ?

**Comment by dkasak** [comment]
Not currently and it's unlikely to be implemented unless someone contributes it. It's a planned feature for [weechat-matrix-rs](https://github.com/poljar/weechat-matrix-rs/), though development has stalled a bit right now.
