### ISSUE TITLE
Alpine Linux install package list required

### ISSUE THREAD

**Issue by vlp-git** [poljar/weechat-matrix#319]
just to share you the packages required in order to pass pip3 requirement for weechat-matrix on alpine:

`apk add weechat weechat-python python3 python3-dev curl olm olm-dev musl-dev gcc py3-wheel py3-importlib-metadata libffi-dev make`

**Comment by 2Belette** [comment]
Thanks vlp very helpful

**Comment by craftyguy** [comment]
you could just package it in Alpine :D

**Comment by craftyguy** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/32400

**Comment by dkasak** [comment]
@craftyguy, thanks for packaging! I'd like to add Alpine installation instructions, but I'm not very familiar with Alpine. Now that there's an aport, how would one install it?

**Comment by craftyguy** [comment]
@dkasak basically just: `sudo apk add weechat-matrix`

then to enable it in weechat: 

```
$ mkdir -p ~/.local/share/weechat/python/autoload
$ ln -s /usr/share/weechat/python/weechat-matrix.py -t ~/.local/share/weechat/python/autoload
```

Those instructions get printed after you `apk add` the package ^^

**Comment by dkasak** [comment]
Great, thanks! There's now https://github.com/poljar/weechat-matrix#alpine-linux.

**Comment by craftyguy** [comment]
@dkasak nice, thanks for documenting it :D

**Comment by vlp-git** [comment]
> ttps://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/32400

Big thanks !!
