### ISSUE TITLE
python: script "matrix.py" not found

### ISSUE THREAD

**Issue by TornaxO7** [poljar/weechat-matrix#336]
hello! I'm using [`artix`](https://artixlinux.org/) and installed the `weechat-matrix` from `community`. Now if I do the following:
1. Execute `weechat`
2. Execute `/script load matrix.py`
then I'm getting the following error message:
```
python: script "matrix.py" not found
```

What am I doing wrong?

**Comment by trygveaa** [comment]
The script is called `weechat-matrix.py` in that package, so you need to run `/script load weechat-matrix.py`.

**Comment by TornaxO7** [comment]
Weeeeeee, it's working! Thanks!
