### ISSUE TITLE
script "matrix.py" not found

### ISSUE THREAD

**Issue by iamstupidhelpme** [poljar/weechat-matrix#339]
Hi. I'm using manjaro linux. Tried to configure weechat using instruction from readme but can't do step 1 because of error:

=!= python: script "matrix.py" not found

**Comment by trygveaa** [comment]
If you installed it with pacman, see https://github.com/poljar/weechat-matrix/issues/336#issuecomment-1323932233

**Comment by iamstupidhelpme** [comment]
Thank you, it worked.
