### ISSUE TITLE
Issue installing - missing python-olm.git@master

### ISSUE THREAD

**Issue by tommyskg** [poljar/weechat-matrix#38]
Hi,

Running ``pip2.7 install -r requirements.txt`` on OpenBSD results in the following error. Am I overlooking anything here, or is there something missing in the python-olm repo?

      Could not find a version that satisfies the requirement python-olm@ git+https://github.com/poljar/python-olm.git@master#egg=python-olm-0 (from matrix-nio@ git+https://github.com/poljar/matrix-nio.git@master#egg=matrix-nio-0->-r requirements.txt (line 9)) (from versions: )

I assume this isn't anything platform-specific, but I'll leave that open as well.

**Comment by poljar** [comment]
Could you please share the OpenBSD  and pip versions.

This is probably an old pip that doesn't understand the new direct URL PEP508 syntax for dependencies.

**Comment by tommyskg** [comment]
Ah - you are absolutely right. Upgrading pip solved it straight away. Sorry about jamming you with a non-issue.

I have some other issues building it the olm lib on OpenBSD as well, but I'll drop that one in the other repo.
