### ISSUE TITLE
Feature request: Send messages to unverified devices

### ISSUE THREAD

**Issue by trygveaa** [poljar/weechat-matrix#53]
If you send a message in Riot without having verified all the devices in the room, you get a warning/prompt which allows you to send the message anyway. The people you haven't verified will still be able to decrypt your message.

It would be nice to have this functionality available, since I don't want to verify a device before I have a secure way of doing so, but I'd still like to send (less secure) messages before I do so.

**Comment by ReK2Fernandez** [comment]
I was just going to post this.. thank you.

**Comment by kechpaja** [comment]
Query: is anyone already working on this? I'm thinking about trying to implement something like this, since I'm getting annoyed by the same problem, but don't want to duplicate any work.

**Comment by poljar** [comment]
As far as I know nobody is working on this.

To add this:

- Extend the nio MatrixStore class so we can mark devices as ignored (this includes two store classes that are children of MatrixStore)
- Modify the share_group_session method in the Olm class to take into account ignored devices.
- Extend the Weechat `/olm` command with a ignore sub-command.
- Optional but nice to have: Add the ability to ignore all devices in a room.

**Comment by poljar** [comment]
@kechpaja did you get anywhere with this or should I take over?

**Comment by kechpaja** [comment]
I'm making progress. I still need to do one or two more things before I have something that's easy to test, but that should be done relatively soon (possibly as early as tomorrow).

**Comment by poljar** [comment]
Ok, great. One thing I remembered, we can modify the share_group_session to take a flag that notifies the function to mark unverified devices as ignored instead of raising an trust error.

That way we get the ignore all devices in a room functionality for free.

**Comment by kechpaja** [comment]
Update: I think I have something that will do the job, but I won't have a moment to test it all out until tomorrow morning or perhaps late tonight.

**Comment by kechpaja** [comment]
Here's the other pull request in the weechat-matrix repo: https://github.com/poljar/weechat-matrix/pull/85.

**Comment by poljar** [comment]
This is now supported using the `send-anyways` command and alternatively sending the same message again if the `matrix.network.resending_ignores_devices` setting is  enabled.
