### ISSUE TITLE
'OlmEvent' object has no attribute 'transaction_id'

### ISSUE THREAD

**Issue by ara4n** [poljar/weechat-matrix#55]
i just gave the plugin a quick spin - looks super promising :) I built python-olm against latest olm from git.matrix.org, and matrix-nio against that, and loaded it up into weechat-2.4. however, on connection, i get:

```
python: stdout/stderr (matrix): Traceback (most recent call last):
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/utf.py", line 91, in wrapper
python: stdout/stderr (matrix):     return function(*decode_from_utf8(args), **decode_from_utf8(kwargs))
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix.py", line 317, in receive_cb
python: stdout/stderr (matrix):     server.handle_response(response)
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/server.py", line 1307, in handle_response
python: stdout/stderr (matrix):     self._handle_sync(response)
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/server.py", line 1199, in _handle_sync
python: stdout/stderr (matrix):     self._handle_room_info(response)
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/server.py", line 1135, in _handle_room_info
python: stdout/stderr (matrix):     room_buffer.handle_joined_room(info)
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/buffer.py", line 1676, in handle_joined_room
python: stdout/stderr (matrix):     self.handle_timeline_event(event)
python: stdout/stderr (matrix):   File "/home/matthew/.weechat/python/matrix/buffer.py", line 1275, in handle_timeline_event
python: stdout/stderr (matrix):     if event.transaction_id:
python: stdout/stderr (matrix): AttributeError: 'OlmEvent' object has no attribute 'transaction_id'
python: error in function "receive_cb"
```

**Comment by poljar** [comment]
Hi, thanks for checking out the script.
Olm events in a timeline, completely forgot about the possibility of those.

Can you check out if this fixes at least the crash: https://github.com/poljar/matrix-nio/commit/62e2c8af2bedc59f53be812b0ba6e4cd0d8a91c6?

**Comment by ara4n** [comment]
ah, yeah - it might be choking on pre-megolm olm-only rooms? (in which case it should perhaps be checking the type of the m.room.encryption event?) testing now...

**Comment by poljar** [comment]
Yeah probably. It is checking the type of the event and the correct algorithm. I don't know how the pre-megolm events looked like. 

If you can give me some source to such an event I'll check out that nio does the right thing.

**Comment by ara4n** [comment]
yeah, that seems to have solved that one. thanks!

**Comment by ara4n** [comment]
(the pre-megolm events look the same as olm events as received as to-device messages etc, but the m.room.encryption algorithm used was `m.olm.v1.curve25519-aes-sha2` rather than `m.megolm.v1.aes-sha2`.)

**Comment by poljar** [comment]
Oh, ok. Makes sense since you got a valid OlmEvent object in the timeline. I guess it's safe to ignore them outside of the to-device dict.

Thanks again for checking this out and for the bug report.
