### ISSUE TITLE
weird mangling on receiving e2e messages from unverified devices

### ISSUE THREAD

**Issue by ara4n** [poljar/weechat-matrix#56]
so, good news: i can receive e2e messages! 

bad news: they're pretty mangled (at least in weechat in a screen)

riot sees:

<img width="597" alt="screenshot 2019-02-23 at 23 24 32" src="https://user-images.githubusercontent.com/1294269/53292905-355d4980-37c2-11e9-8749-22c1a9a890cd.png">

weechat shows:

```
23:19:00        =!= | matrix: This room is encrypted, encryption is currently unsuported. Message sending is disabled for this room.  
22:43:12 M-b~ZM- M- | test&matthew                                                                                                    
23:19:27 M-b~ZM- M- | rightmatthew                                                                                                    
23:19:29 M-b~ZM- M- | any better?w                                                                                                    
23:20:15        =!= | matrix: Untrusted devices found in room: Device NBHCUILQXV for user @matthew:matrix.org is not verified or      
                    | blacklisted.                                                                                                    
```

however, having run `/olm verify @matthew:matrix.org *`, it now seems to be working for receiving okay?

**Comment by poljar** [comment]
That sounds like the extra warning sign we're adding at the front of the user name is messing things up for you.

You can check if my suspicion is correct by changing the setting `matrix.look.encryption_warning_sign` to something else, by default it's a emoji warning sign (⚠️) which may not work for everybody.

**Comment by ara4n** [comment]
ah, right - i suspect it's the weechat + screen combo choking on the emoji. will check.

**Comment by poljar** [comment]
There are a couple of those emoji signs, they are all under the `matrix.look` config section. We should probably set those to some safer ascii only defaults.

**Comment by ara4n** [comment]
yup, it chokes horribly on all emoji; looks like a terminal screwup.

**Comment by ara4n** [comment]
turns out this is because i didn't have libncursesw installed. weechat's configure had warned me about it but i missed the warning:

```
*** ncursesw library not found! Falling back to "ncurses"
*** Be careful, UTF-8 display may not work properly if your locale is UTF-8.
```

having installed and rebuilt, all is \o/

**Comment by poljar** [comment]
Oh, nice.

**Comment by ara4n** [comment]
for the sake of completeness... i then also had weird problems with rooms with emoji corrupting the screen when you switch away from the room and looking like this:

<img width="992" alt="screenshot 2019-02-24 at 00 32 27" src="https://user-images.githubusercontent.com/1294269/53293597-b6224280-37ce-11e9-829d-4f3633373dd6.png">

Turns out this was a bad interaction with gnu screen: https://savannah.gnu.org/bugs/index.php?50044 is the root bug (also https://github.com/weechat/weechat/issues/854#issuecomment-275316973). upgrading from screen 4.5 (in debian stable) to a handbuilt 4.6 fixed it, and it's all working amazingly now :)
