### ISSUE TITLE
Whatsapp bridge display names

### ISSUE THREAD

**Issue by ptman** [poljar/weechat-matrix#59]
I'm using https://github.com/tulir/mautrix-whatsapp and while the lua plugin shows somewhat readable whatsapp user names, this python plugin shows whatsapp_$phonenr (for AS user @whatsapp_$phonenr:example.com). Apparently there is already some fix for IRC and more work underway in https://github.com/poljar/weechat-matrix/pull/28

This probably also depends on the AS registration config.

**Comment by poljar** [comment]
Whatsapp users don't have any unique user name in the full user id? If so we'll have to use the display name in the hack just like it's done for discord users.

**Comment by ptman** [comment]
ah &lt;phonenr&gt; was hidden, so I replaced it with $phonenr

**Comment by ptman** [comment]
Oh, as long as we're extending the hack in https://github.com/poljar/weechat-matrix/commit/e9e61b04da0083fed18173caf73f8428d802579a , should we also handle gitter? I think there are some gitter users in #matrix:matrix.org . They generally have the form of gitter_$username

**Comment by poljar** [comment]
Added a workaround for gitter as well as xmpp users to the whatsapp branch.
