### ISSUE TITLE
Server Buffers in Wrong Location

### ISSUE THREAD

**Issue by gyroninja** [poljar/weechat-matrix#61]
All of the server buffers for matrix servers are attached to the main weechat buffer. This means that they contain the same log messages minus the prefix. Additionally, if you try to move any one of the buffers around they it will move the weechat buffer along with all the matrix server buffers. I am not able to drag channels in between multiple matrix servers.
Right now all of the matrix channels I'm in are added after my weeslack buffers (after the last weeslack channel).

**Comment by poljar** [comment]
Hi.
There is a setting called `matrix.look.server_buffer` that mimics the same setting for the IRC plugin. With that setting you can chose if you want the matrix server buffers merged with the core Weechat buffer, merged with other matrix server buffers or completely independent.

**Comment by gyroninja** [comment]
This resolves half of the issue. There is still an issue with all of the channel buffers being put after the last weeslack one instead of under the matrix server buffers. With setting `matrix.look.server_buffer` to independent the server buffers are now correctly being placed after the weeslack related buffers, which I figure is from loading weeslack first. Thankfully I can just drag the channels and stuff around to at least fix it for as long as I keep my weechat open.

**Comment by poljar** [comment]
Buffers are by default placed by Weechat at the end of the list. I agree that we could place new buffers automatically a little bit better like the IRC plugin does with the `irc.look.new_channel_position` setting. There is also [this](https://weechat.org/scripts/source/autosort.py.html) script to sort buffers based on patterns and of course the `/layout` command works as usual.

**Comment by gyroninja** [comment]
Thanks for the information.
>at the end of the list
I would quite describe what's going on like that.
Here's a simplified example of before and after the matrix channels getting added.
Before
[slack server]
[slack channel]
[matrix server]
[irc server]
[irc channel]
After
[slack server]
[slack channel]
[matrix channel]
[matrix server]
[irc server]
[irc channel]

**Comment by jessfraz** [comment]
so the autosort.py plugin makes manually moving them kinda impossible, is there another work-around?

**Comment by poljar** [comment]
What do you wish to achieve? Unless this gets ported https://github.com/weechat/weechat/blob/master/src/plugins/irc/irc-channel.c#L75 to weechat-matrix buffers won't start spawning near the server.

The autosort.py script can be configured to sort as you wish. Please see the auto-sort help to learn how to write auto-sort rules.

To make auto-sort honor your layouts you can use the `${buffer.layout_number}` in a auto-sort rule.
