### ISSUE TITLE
Crash/exit on load

### ISSUE THREAD

**Issue by u3shit** [poljar/weechat-matrix#63]
Try to install requrements:
```
$ pip2 install --user -r requirements.txt
Requirement already satisfied: pyOpenSSL in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting typing (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Collecting webcolors (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/1d/44/c4902683be73beba20afd299705e11f0a753a01cc7f9d6a070841848605b/webcolors-1.8.1-py2.py3-none-any.whl
Collecting future (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 917kB/s
Collecting atomicwrites (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting attrs (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting logbook (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/f6/83/20fc0270614919cb799f76e32cf143a54c58ce2fa45c19fd38ac2e4f9977/Logbook-1.4.3.tar.gz (85kB)
    100% |████████████████████████████████| 92kB 1.0MB/s
Collecting pygments (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
    100% |████████████████████████████████| 849kB 549kB/s
Collecting matrix-nio@ git+https://github.com/poljar/matrix-nio.git@master#egg=matrix-nio-0 (from -r requirements.txt (line 9))
  Could not find a version that satisfies the requirement matrix-nio@ git+https://github.com/poljar/matrix-nio.git@master#egg=matrix-nio-0 (from -r requirements.txt (line 9)) (from versions: )
No matching distribution found for matrix-nio@ git+https://github.com/poljar/matrix-nio.git@master#egg=matrix-nio-0 (from -r requirements.txt (line 9))
```
Um, clone matrix-nio manually and install the dependencies from it... pycrypto configure script can't figure out how to invoke gcc. Install pycrypto from gentoo, try again, it works.
Install with `make install`, copy `nio` directory next to `matrix` (because of the pip problem above), try `/script load matrix.py test`.
Figure out `olm` is missing from the dependencies. Install it manually, and try again:
Weechat just exits. No error message, no SIGSEGV in dmesg, it just exits with exit code 2. At least the older lua implementation more or less worked.

Weechat 2.3, Python 2.7, gentoo stable.

**Comment by poljar** [comment]
Hi there.

It's hard to tell why matrix-nio fails to install from requirements, could be that you're using an old pip that doesn't understand direct URL dependencies or maybe because one of the matrix-nio dependencies failed to install.

I don't think I want to provide support on how to install pycrypto since I install it from my distro repository and have no idea why it might fail for you. That being said, you're probably missing some C dependencies for pycrypto. You can also use the [pycryptodome](https://pycryptodome.readthedocs.io/en/latest/src/installation.html) library instead of pycrypto since it's an drop in replacement. 

Maybe we should switch to pycryptodome since it seems to be the more popular package.

Where did you see that olm is missing from the dependencies? It's right [here](https://github.com/poljar/matrix-nio/blob/master/setup.py#L27).

I also don't know why weechat might be exiting, from the wild ride you had while installing the dependencies it could be that something isn't installed right, we had weird issues because of incomplete installs before.

You could try to import olm from a python interpreter and try to create a olm `Account` object with:
```python
import olm
acc = olm.Account()
```
If that doesn't fail python-olm is working. Next step would be to try to do the same with matrix-nio.

**Comment by u3shit** [comment]
Hi,

> It's hard to tell why matrix-nio fails to install from requirements, could be that you're using an old pip that doesn't understand direct URL dependencies or maybe because one of the matrix-nio dependencies failed to install.I have the latest pip in gentoo stable, which is 9.0.1

> I don't think I want to provide support on how to install pycrypto since I install it from my distro repository and have no idea why it might fail for you. That being said, you're probably missing some C dependencies for pycrypto. You can also use the [pycryptodome](https://pycryptodome.readthedocs.io/en/latest/src/installation.html) library instead of pycrypto since it's an drop in replacement. 
I've installed pycrypto from from my package manager, it worked. Maybe
it had to add some random compile flags, I didn't check, but it didn't
have to install any extra packages so I should have everything...

> Where did you see that olm is missing from the dependencies? It's right [here](https://github.com/poljar/matrix-nio/blob/master/setup.py#L27).
Um, I checked the rtd-requirements.txt file in matrix-nio, it doesn't
have it.

> You could try to import olm from a python interpreter and try to create a olm `Account` object with:
> ```python
> import olm
> acc = olm.Account()
> ```

```
>>> import olm
usage: [-h] [-i] [-d] [-r] [-s SETTINGS] [-l LOG_LEVEL] src
: error: too few arguments
```
And it exits with exit code 2. Wtf? I'll try to reinstall olm from that
repo and try again.

**Comment by poljar** [comment]
pip [9.0.1](https://pip.pypa.io/en/stable/news/#id97) is from 2016, and indeed it is missing the support for the new direct URL dependencies.

The rtd-requirements.txt file, as the name of the file might hint to, is the requirements file for readthedocs. Since you can't install arbitrary C packages on readthedocs and python-olm requires the C Olm library it can't be in the requirements file while installing on readthedocs.

Where did you try to run that `import olm` statement? What program gave that usage output and `too few arguments` error?

**Comment by u3shit** [comment]
>9.0.1 is old
Well, gentoo has 10.0.1 in unstable...

If I replace the matrix-nio line in requirements.txt with `git+https://github.com/poljar/matrix-nio.git@master#egg=matrix-nio`, it finds it. I don't know what is that funny syntax you use, I can't even find it in the stable pip documentation: https://pip.pypa.io/en/stable/reference/pip_install/#requirement-specifiers

Trying to install olm:
```
$ pip2 install --user git+https://github.com/poljar/python-olm.git@master#egg=python-olm
Collecting python-olm from git+https://github.com/poljar/python-olm.git@master#egg=python-olm
  Cloning https://github.com/poljar/python-olm.git (to master) to /tmp/pip-build-fnYG_J/python-olm
Requirement already satisfied: cffi>=1.0.0 in /usr/lib64/python2.7/site-packages (from python-olm)
Collecting future (from python-olm)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting typing (from python-olm)
  Using cached https://files.pythonhosted.org/packages/cc/3e/29f92b7aeda5b078c86d14f550bf85cff809042e3429ace7af6193c3bc9f/typing-3.6.6-py2-none-any.whl
Requirement already satisfied: pycparser in /usr/lib64/python2.7/site-packages (from cffi>=1.0.0->python-olm)
Installing collected packages: future, typing, python-olm
  Running setup.py install for future ... done
  Running setup.py install for python-olm ... error
    Complete output from command /usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fnYG_J/python-olm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x7ms8R-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/olm
    copying olm/__init__.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/__version__.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/_compat.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/_finalize.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/account.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/group_session.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/pk.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/session.py -> build/lib.linux-x86_64-2.7/olm
    copying olm/utility.py -> build/lib.linux-x86_64-2.7/olm
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-2.7/_libolm.c'
    creating build/temp.linux-x86_64-2.7
    building '_libolm' extension
    creating build/temp.linux-x86_64-2.7/build
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_libolm.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_libolm.o
    build/temp.linux-x86_64-2.7/_libolm.c:493:18: fatal error: olm/olm.h: No such file or directory
             #include <olm/olm.h>
                      ^~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fnYG_J/python-olm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-x7ms8R-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-fnYG_J/python-olm/
```

Am I supposed to install some random c library?

**Comment by u3shit** [comment]
Alright, fortunately it looks like there's an ebuild for matrix-nio and its metric fucktons of dependencies (almost), in an overlay (http://gpo.zugaina.org/dev-python/matrix-nio), so I ended up with installing from it. Now it seems like working.

**Comment by poljar** [comment]
The link to the documentation you gave contains a link to PEP 508 which specifies the syntax, you can see an URL example of the syntax [here](https://www.python.org/dev/peps/pep-0508/#examples).

As the name might suggest, python-olm is just a library that provides higher level python bindings to the Olm C library which can be found [here](https://git.matrix.org/git/olm/). So you'll need to install that as well.

**Comment by poljar** [comment]
Glad you got it working.

**Comment by u3shit** [comment]
Actually, it might be helpful to document this fact, that a dependency of a dependency has a dependency on a c library, because the readme only mentions having to install a few python packages, and nio's readme doesn't mention any dependencies. I guess few users will start to read setup.py to figure out there's a dependency which depends a c package.

**Comment by poljar** [comment]
Sorry, I didn't yet get to documenting the nio install process. It will be eventually improved/documented.

If you have the time please feel free to improve the nio or even the weechat-matrix README file and open up a pull request.
