### ISSUE TITLE
/script load matrix.py fails on Arch

### ISSUE THREAD

**Issue by sammoth** [poljar/weechat-matrix#64]
I get this but it's not clear what file is missing:

         │14:20:20 weechat     | python: loading script "/home/sam/.weechat/python/matrix.py"
         │14:20:20 weechat     | python: stdout/stderr (?): Traceback (most recent call last):
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.weechat/python/matrix.py", line 34, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from nio import RemoteProtocolError, RemoteTransportError, TransportType
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/matrix_nio-0.1-py2.7.egg/nio/__init__.py", line 2, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from .client import HttpClient, TransportType, Client
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/matrix_nio-0.1-py2.7.egg/nio/client.py", line 46, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from .crypto import Olm
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/matrix_nio-0.1-py2.7.egg/nio/crypto/__init__.py", line 19, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from .olm_machine import Olm  
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/matrix_nio-0.1-py2.7.egg/nio/crypto/olm_machine.py", line 40, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from jsonschema import SchemaError, ValidationError
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/jsonschema-3.0.1-py2.7.egg/jsonschema/__init__.py", line 22, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from jsonschema._types import TypeChecker
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/home/sam/.local/lib/python2.7/site-packages/jsonschema-3.0.1-py2.7.egg/jsonschema/_types.py", line 3, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     from pyrsistent import pmap
         │14:20:20 weechat     | python: stdout/stderr (?):   File "build/bdist.linux-x86_64/egg/pyrsistent/__init__.py", line 3, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):   File "build/bdist.linux-x86_64/egg/pyrsistent/_pmap.py", line 4, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):   File "build/bdist.linux-x86_64/egg/pyrsistent/_pvector.py", line 699, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):   File "build/bdist.linux-x86_64/egg/pvectorc.py", line 7, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):   File "build/bdist.linux-x86_64/egg/pvectorc.py", line 3, in __bootstrap__
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
         │14:20:20 weechat     | python: stdout/stderr (?):     @_call_aside
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
         │14:20:20 weechat     | python: stdout/stderr (?):     f(*args, **kwargs)
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
         │14:20:20 weechat     | python: stdout/stderr (?):     working_set = WorkingSet._build_master()
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
         │14:20:20 weechat     | python: stdout/stderr (?):     ws = cls()
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 567, in __init__
         │14:20:20 weechat     | python: stdout/stderr (?):     self.add_entry(entry)
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 623, in add_entry
         │14:20:20 weechat     | python: stdout/stderr (?):     for dist in find_distributions(entry, True):
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2007, in find_on_path
         │14:20:20 weechat     | python: stdout/stderr (?):     path_item = _normalize_cached(path_item)
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2317, in _normalize_cached
         │14:20:20 weechat     | python: stdout/stderr (?):     _cache[filename] = result = normalize_path(filename)
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2299, in normalize_path
         │14:20:20 weechat     | python: stdout/stderr (?):     return os.path.normcase(os.path.realpath(os.path.normpath(_cygwin_patch(filename))))
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/posixpath.py", line 383, in realpath
         │14:20:20 weechat     | python: stdout/stderr (?):     return abspath(path)
         │14:20:20 weechat     | python: stdout/stderr (?):   File "/usr/lib/python2.7/posixpath.py", line 371, in abspath
         │14:20:20 weechat     | python: stdout/stderr (?):     cwd = os.getcwd()
         │14:20:20 weechat     | python: stdout/stderr (?): OSError: [Errno 2] No such file or directory
         │14:20:20 weechat =!= | python: unable to parse file "/home/sam/.weechat/python/matrix.py"
         │14:20:51 weechat     | python: 2.7.15

**Comment by poljar** [comment]
Seems like something is broken with the new 3.0 version of jsonschema. It hasn't landed in the arch repos yet.

You can quite easily install python-olm and matrix-nio as an arch package with:
`make arch-git-pkg` for matrix-nio and `make archpkg` for python-olm. I should probably upload some PKGBUILDS to the AUR to make this even easier.

**Comment by sammoth** [comment]
Thanks that worked
