### ISSUE TITLE
can't type on an encrypted channel[fixed]

### ISSUE THREAD

**Issue by ReK2Fernandez** [poljar/weechat-matrix#68]
and I believe I have accepted all keys.. I can read fine, just can't type anything... I am trying to look at the code to see if there is an option for this but so far can't see one.. so sorry if I am missing an option or something.

**Comment by ReK2Fernandez** [comment]
ok I found out that if you are missing one single key it will not allow you to write... I will suggest that you get a warning and ask you to submit anyways or not...

**Comment by poljar** [comment]
Which key is missing, a device that we want to talk to doesn't contain keys? I believe that should work, but I might have broken it while fixing other stuff.

**Comment by ReK2Fernandez** [comment]
@poljar no, simpler than that,if there is someone in the room that has not shared my keys and I do not  blacklist him or make sure I added everyone to /old verify @person:domain.com I can read msg but can't type. so was asking that a warning should be enough.

**Comment by poljar** [comment]
This was fixed by c400404e3dd9a1806516348360388813b1efe850.
