### ISSUE TITLE
keep getting disconnected

### ISSUE THREAD

**Issue by ReK2Fernandez** [poljar/weechat-matrix#69]
Not sure why or if I need to twink/add/change a time out setting or something but I keep getting disconnected and then connected over and over... 
any idea?
thanks

**Comment by poljar** [comment]
Is there a traceback/error or is it just a normal disconnect? If there is no big crashing error this might be a dupe of #30.

**Comment by ReK2Fernandez** [comment]
no error just disconnects and connects again.. sometimes im chatting and all of the sudden im offline and have to wait 10 secs.. so gets annoying. So im not sure if this is something I need to increment on my side or a bug.

**Comment by ReK2Fernandez** [comment]
@poljar here is a screenshot.
![weechat-matrix-error](https://user-images.githubusercontent.com/5316229/54945418-fc181680-4ef2-11e9-926d-52b6f717b23b.png)

**Comment by dkasak** [comment]
Yeah, that looks like #30. The essence is that this is an UX issue: weechat-matrix should probably not display connection closures as prominently and should allow queueing new messages while there is no connection.

**Comment by ReK2Fernandez** [comment]
@poljar @dkasak I been reading the issues you guys linked, and yes is similar only in my case I am using the latest github master so in your issue you said you fix or added an option.. also in my case is super annoying when this happens I cant type, I have to wait... so if I am explaining something long to someone every 10secs I have to wait... then type then wait then type then wait... almost unusable.

**Comment by ReK2Fernandez** [comment]
@dkasak @poljar here is a screenshot of how this is making my use almost impossible. Notice all the "you are not connected" right in between all my conversations.. I have to wait constantly... 
![not-connected-to-server](https://user-images.githubusercontent.com/5316229/55253738-6098e580-5213-11e9-9b6c-ee4a66623989.png)

**Comment by poljar** [comment]
Are you using your own server? The problem with not noticing new Olm devices might be related to this as well (Yes bad connections should be handled better either way). 

If you can configure the server you can try setting a really high keep-alive for HTTP but even better enable HTTP2 and set the maximum number of requests to something high (e.g. for nginx [this](http://nginx.org/en/docs/http/ngx_http_v2_module.html#http2_max_requests) setting).

**Comment by ReK2Fernandez** [comment]
yes we using our own server, and the hardware is good.. is in digital ocean 8 gigs of ram and 8 cpu's we only like 40 users. I will try the HTTP/2 and check for http time outs... I do not remember from top of my head how we have it and Im at work now. thanks.

**Comment by ReK2Fernandez** [comment]
Enabled http2 on nginx.. have not yet incremented keepalive and so far still getting disconnects.

**Comment by ReK2Fernandez** [comment]
> Enabled http2 on nginx.. have not yet incremented keepalive and so far still getting disconnects.

nevermind :)  I only changed it for ipv6 now is set for both
```
Yeah! matrix.hispagatos.org supports HTTP/2.0
```
so far so good.. going to wait some time before I give this as resolved.

**Comment by ReK2Fernandez** [comment]
hello is confirmed  adding http/2 support and the linked option to nginx solved this issue. thanks <3
