### ISSUE TITLE
Issues with sync/account log in , nio.response, python 2 build

### ISSUE THREAD

**Issue by quietok** [poljar/weechat-matrix#81]
matrix: Logged in as @imacat:matrix.org
nio.responses: Error validating response: u'!Pollux_Awakes_Twilight_Velvet:ponies.im' does not match any of the regexes: u'^![a-zA-Z0-9]+:.+$'
matrix: Error: SyncError: 200 unknown error

Using python2 build

**Comment by poljar** [comment]
I seem to remember room ids having a defined grammar but i can't find that in the spec anymore, could you try this patch for nio out and confirm that it fixes the issue https://github.com/poljar/matrix-nio/commit/c574fb247566f6a33e05c090e7e8444f7dc6d336?

**Comment by quietok** [comment]
Yep the patch worked, connecting fine now! Thank you kind sir.

**Comment by poljar** [comment]
Thanks for testing. Pushed to the master branch of nio.
