### ISSUE TITLE
Installation instructions for olm are misleading

### ISSUE THREAD

**Issue by strk** [poljar/weechat-matrix#82]
The README.md file says for Debian/Ubuntu to look in https://gitlab.matrix.org/matrix-org/olm but there are no instructinos there

**Comment by poljar** [comment]
What do you mean by no  instructions? It instructs you to either use make or cmake.

**Comment by poljar** [comment]
The docker file has the steps laid out as well https://github.com/poljar/weechat-matrix/blob/master/Dockerfile#L32

**Comment by strk** [comment]
I mean there are no instructions to install binaries for Debian/Ubuntu.
Building from sources would not be specific to operating system...

**Comment by strk** [comment]
I'm referring to: "Debian/Ubuntu (see https://git.matrix.org/git/olm)" written here: https://github.com/poljar/weechat-matrix/blob/master/README.md#installation

Note that `libolm-dev` 2.2.2 is packaged in at least Ubuntu 18.04.1 LTS, but the README of weechat-matrix does not say if it is good to use.

**Comment by strk** [comment]
#88 is my proposal to fix this
