### ISSUE TITLE
Feature Request: Message Replies

### ISSUE THREAD

**Issue by BurnyBoi** [poljar/weechat-matrix#86]
Just like the reply feature on Riot, a way to reference a particular message in your message. It could function similar to the /redact command, where you type /reply, then tab through the messages until you see the message text for the message you wish to reply to. Then, whatever you type after that would be the reply. 

Example:
`/reply $38j9328jd98j983jd923:"What day is Memorial day?" May 27th`

The resulting message should look just like how a reply would look when done on Riot.

**Comment by myii** [comment]
I've managed to hack something together based on this idea.  I'm sure the implementation will need cleaning up but it's pretty simple overall.  @poljar Are you interested in a PR for this?

**Comment by poljar** [comment]
Sure, if it works I'll be happy to merge.
