### ISSUE TITLE
bug with python 2.x and 3.x

### ISSUE THREAD

**Issue by ReK2Fernandez** [poljar/weechat-matrix#90]
Keep getting this type of errors all the time.. did not notice until now, been having to do /reload 
![weechat-matrix-bug](https://user-images.githubusercontent.com/5316229/58197192-09bc0380-7ccc-11e9-8482-c5bc56e9465c.png)

**Comment by poljar** [comment]
That's a peewee bug that got fixed https://github.com/coleifer/peewee/issues/1913#issue-437758553.
