### ISSUE TITLE
After todays git pull having new issues

### ISSUE THREAD

**Issue by ReK2Fernandez** [poljar/weechat-matrix#91]
Here is a screenshot says something about OLM missing Sas
![weechat-matrix-bug1](https://user-images.githubusercontent.com/5316229/58487058-445beb00-8167-11e9-9282-ce04f0919a35.png)

**Comment by poljar** [comment]
You'll need to update C libolm library as well, 3.1+ is now required for the emoji based key verification.

**Comment by ReK2Fernandez** [comment]
ok let me look for this.

**Comment by ReK2Fernandez** [comment]
I have this one installed ... seems should be the right one, but will try the -git version instead
```
aur/libolm 3.1.2-1 (+10 0.70%) (Installed)
```

**Comment by ReK2Fernandez** [comment]
hmm no luck...  I have installed the git version...
```
aur/libolm-git 2.2.2.r6.g001dc1e-1 (+0 0.00%) (Installed: 3.1.2.r12.ga18a4e8-1)
    An implementation of a well known cryptographic ratchet in C++
aur/libolm 3.1.2-1 (+10 0.70%) 
    An implementation of the Double Ratchet cryptographic ratchet in C++
```

**Comment by poljar** [comment]
No, this one is correct. Make sure to have python-olm 3.1 as well (can be found on the AUR as well). Also make sure to restart weechat since it doesn't seem to pickup new libraries just from a script reload.

**Comment by ReK2Fernandez** [comment]
ok installing python-olm did the trick thanks <3
