### ISSUE TITLE
How to get an "username" and "password" on matrix.org

### ISSUE THREAD

**Issue by KebabLord** [poljar/weechat-matrix#98]
I recompiled weechat to run with python3 and finally matrix is working but while configuring I didn't understand which usernames and password we are setting. There is no registiration section I found in entire site. So my question is where to get an uname and password.

**Comment by poljar** [comment]
weechat-matrix doesn't support registration currently. You'll have to use another client for that. To get an account on matrix.org you can check out [riot](https://riot.im/app/).

**Comment by KebabLord** [comment]
thanks, done
